# Generated by Django 4.2.2 on 2025-04-03 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_place_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('pubdate', models.DateField(max_length=100)),
                ('cover', models.CharField(max_length=100)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.place')),
            ],
        ),
    ]
