# Generated by Django 4.2.2 on 2025-04-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_cover_alter_book_isbn_alter_book_pubdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='is_active',
        ),
    ]
