# Generated by Django 4.2.2 on 2025-04-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_place_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
