# Generated by Django 4.2.2 on 2025-04-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_is_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pubdate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
