# Generated by Django 4.2.2 on 2025-04-09 04:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0010_lenging'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lenging',
            new_name='Lending',
        ),
    ]
