# Generated by Django 4.2.2 on 2025-04-09 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_rename_lenging_lending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
