# Generated by Django 4.2.2 on 2025-04-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_lending_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lending',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
