# Generated by Django 4.2.2 on 2025-04-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_review_rating_alter_review_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authorkana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pubkana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='titlekana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
