# Generated by Django 4.2.2 on 2025-04-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_author_alter_book_authorkana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
