# Generated by Django 4.2.2 on 2025-04-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_created_at_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='borrow',
            field=models.BooleanField(default=False),
        ),
    ]
