# Generated by Django 4.2.2 on 2025-04-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_borrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='borrow',
        ),
    ]
